1. Cargad el csv que guardasteis ayer.

Antes de seguir con las preguntas, este DataFrame está terriblemente sucio. En las próximas sesiones lo iremos limpiando. Para evitar posibles errores con los nulos vamos a eliminar todos los nulos del DataFrame.
Para ello vamos a utilizar el método .dropna() de pandas. Tendréis que ejecutar la siguiente línea de código para eliminar los nulos del DataFrame y poder seguir haciendo el resto de los ejercicios.

In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv('../DATA/attacks_Pandas_3.csv')
df

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25
1,2018.06.18,1,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18
2,2018.06.09,2,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09
3,2018.06.08,3,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08
4,2018.06.04,4,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6109,1804.02.26.R,6127,1804.0,Boat,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",NaN,boat,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1804.02.26.R
6110,1803.05.17,6128,1803.0,Sea Disaster,USA,South Carolina,Off Charleston,NaN,Captain Jones,M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.05.17
6111,1803.03.00,6129,1803.0,Unprovoked,AUSTRALIA,Western Australia,"Hamelin Harbour, at Faure Island",NaN,M. Lefevre & a sailor (rescuer),M,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1803.03.00
6112,1802.04.13.R,6130,1802.0,Unprovoked,INDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1802.04.13.R
6113,1801.12.18.R,6131,1801.0,Provoked,NaN,NaN,NaN,Standing on landed shark's tail,Stephen Pettigew,N,NaN,NaN,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1801.12.18.R

In [11]:
dfc = df.copy() # creamos una copia de la original, para poder editar la original

In [12]:
df.dropna(inplace = True)
df

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24
13,2018.05.13.a,13,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5528,1901.07.30,5545,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1901.07.30
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1894.11.28
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1892.03.02
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1880.11.25
5905,1868.05.13,5922,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,http://sharkattackfile.net/spreadsheets/pdf_di...,1868.05.13

¿Cuántas filas se han eliminado con esta línea de código?

In [13]:
dfc.shape[0] - df.shape[0] 
# Se han eliminado 4612 filas (diferencia de filas entre la df inicial y la editada)

4612

2. ¿Cuál es el número de ataques que se han producido en Estados Unidos?

In [14]:
df[df['country']== 'USA']

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b
35,2018.03.31,35,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.03.31
53,2017.12.31,53,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.12.31
60,2017.11.24,60,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4731,1941.06.15,4743,1941.0,Provoked,USA,New York,15 miles south of Jones Inlet,Fishing from 32' boat,Paul Ruhle,M,43,14h00,2.1 m [7'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1941.06.15
4734,1941.03.09,4746,1941.0,Provoked,USA,California,"Santa Monica, Los Angeles County",Fishing,Frank Martinez,M,53,Night,Mako shark (aka bonito shark) 1.2 m [4'],http://sharkattackfile.net/spreadsheets/pdf_di...,1941.03.09
4862,1936.07.25,4874,1936.0,Unprovoked,USA,Massachusetts,"Hollywood Beach, just above Mattapoisett Harbo...",Swimming crawl stroke,"Joseph Troy, Jr",M,16,15h30,White shark (identified by Dr. Hugh Smith),http://sharkattackfile.net/spreadsheets/pdf_di...,1936.07.25
5136,1926.07.08,5148,1926.0,Unprovoked,USA,California,"San Francisco Bay (or San Leandro Bay), near c...",Swimming with dog near canning factory,Norman Piexotto,M,15,,1.5 m [5'] white shark or sevengill shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1926.07.08
5297,1916.07.01,5311,1916.0,Unprovoked,USA,New Jersey,"Beach Haven, Ocean County",Swimming,Charles E. Vansant,M,24,17h00,Thought to involve a 2.6 m [8.5'] white shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1916.07.01

3. ¿Y en España?

 3.1  ¿En qué regiones se han producido los ataques?
 
 3.2  ¿Cuántos ataques se han producido en cada área?

In [15]:
# 3
df[df['country']== 'SPAIN']

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
98,2017.08.26.b,98,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.08.26.b
233,2016.07.29,234,2016.0,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,11h30,Blue shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.07.29
377,2015.08.18.a,378,2015.0,Invalid,SPAIN,Alicante,"Poniente Beach, Benidorm",Swimming,male,M,10,11h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.08.18.a
1007,2010.07.16.b,1011,2010.0,Provoked,SPAIN,Grand Canary Island,"Sardina del Norte, Gáldar",Swimming,male,M,9,19h15,Angel shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2010.07.16.b
2469,1993.09.03,2476,1993.0,Unprovoked,SPAIN,Costa Blanca,"Playa de las Arenas, Valencia",Swimming,Jorge Durich Heredia (or Hernandez),M,69,08h00,1.2 m [4'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1993.09.03

In [16]:
#3.1
## VERSION LARGA DE CODIGO

c1 = df[df['country']=='SPAIN']
c1['area'].unique()

array(['Castellón', 'Alicante Province', 'Alicante',
       'Grand Canary Island', 'Costa Blanca'], dtype=object)

In [17]:
#3.1
## CODIGO OPTIMIZADO

df[df['country']=='SPAIN']['area'].unique()

array(['Castellón', 'Alicante Province', 'Alicante',
       'Grand Canary Island', 'Costa Blanca'], dtype=object)

In [18]:
#3.2
df[df['country']=='SPAIN']['area'].value_counts()

Castellón              1
Alicante Province      1
Alicante               1
Grand Canary Island    1
Costa Blanca           1
Name: area, dtype: int64

4.Extraed un DataFrame nuevo con los ataques que se han producido en Australia y Estados Unidos. 📌 Nota Este ejercicio se puede resolver usando dos condiciones de filtrado o usando el método isin(). Hacedlo con ambas herramientas.

4.1 ¿Cuántos ataques se han producido en cada país?

4.2 ¿Ha habido ataques en Australia a gente que estuviera remando (lo encontrareis como Paddling en el DataFrame en la columna activity)?

4.3 ¿Cuántos ataques se han producido en Australia antes del 2000?

4.4 ¿Y después del 2000?

In [19]:
df4 = df[(df['country']== 'USA')|(df['country']=='AUSTRALIA')]
df4['country'].unique()

array(['USA', 'AUSTRALIA'], dtype=object)

In [20]:
isn = df['country'].isin(['AUSTRALIA','USA'])
df4_ = df[isn]
df4_['country'].unique()

array(['USA', 'AUSTRALIA'], dtype=object)

In [21]:
# 4.1 ataques por país

In [22]:
df4[df4['country']== 'AUSTRALIA']['country'].value_counts()

AUSTRALIA    324
Name: country, dtype: int64

In [23]:
df4[df4['country']== 'USA']['country'].value_counts()

USA    719
Name: country, dtype: int64

In [24]:
# 4.2 ataques mientras hacian paddling?

In [25]:
australia = df4[df4['country']== 'AUSTRALIA']
australia[australia['activity']== 'Paddling']['activity'].value_counts()

Series([], Name: activity, dtype: int64)

In [26]:
usa = df4[df4['country']== 'USA']
usa[usa['activity']== 'Paddling']
usa[usa['activity']== 'Paddling']['activity'].value_counts()

Paddling    1
Name: activity, dtype: int64

In [27]:
# 4.3 ataques en australia antes del 2000

In [28]:
australia[australia['year']< 2000]

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
2116,1999.05.29,2123,1999.0,Unprovoked,AUSTRALIA,South Australia,"Hardwicke Bay, Yorke Peninsula",Windsurfing,Tony Donoghue,M,22,14h30,Thought to involve a white shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1999.05.29
2129,1999.02.23,2136,1999.0,Unprovoked,AUSTRALIA,New South Wales,Scotts Head,Surfing,male,M,35,Evening,Bronze whaler or tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1999.02.23
2174,1998.06.28.a,2181,1998.0,Unprovoked,AUSTRALIA,South Australia,South Neptune Island,Free diving for abalone,Doug Chesser,M,26,14h00,Thought to involve a 5.5 m white shark named Kong,http://sharkattackfile.net/spreadsheets/pdf_di...,1998.06.28.a
2194,1998.01.28.R,2201,1998.0,Invalid,AUSTRALIA,New South Wales,Whale Beach,Spearfishing,male,M,31,20h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...,1998.01.28.R
2207,1997.11.09,2214,1997.0,Unprovoked,AUSTRALIA,Western Australia,Albany,Scuba diving (submerged riding a scooter),Kevin Hulkes,M,42,Morning,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.11.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5359,1912.01.26,5375,1912.0,Unprovoked,AUSTRALIA,New South Wales,"Fig Tree Bridge, Lane Cove River, near Sydney",Swimming,James Edward Morgan,M,21,15h00,"2.8 m [9'3""] whaler shark captured 3 days late...",http://sharkattackfile.net/spreadsheets/pdf_di...,1912.01.26
5481,1905.03.26,5498,1905.0,Unprovoked,AUSTRALIA,New South Wales,Lismore,Bathing,Richard Owen,M,40,Morning,5' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1905.03.26
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1894.11.28
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1892.03.02
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1880.11.25

In [29]:
# 4.4, ataques en australia despues del 2000

In [30]:
australia[australia['year']> 2000]

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24
21,2018.04.25.a,21,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.04.25.a
36,2018.03.14,36,2018.0,Unprovoked,AUSTRALIA,Western Australia,Waterman's Bay,Wading,Luke Guy & Finn Bald,M,10,17h35,Wobbegong shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.03.14
37,2018.03.09.b,37,2018.0,Unprovoked,AUSTRALIA,Victoria,Lorne,Swimming,Rob Crossland,M,69,15h30,3.5 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.03.09.b
38,2018.03.09.a,38,2018.0,Unprovoked,AUSTRALIA,Victoria,Winkipop,Surfing,Lachie Brown,M,18,07h30,1.8 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.03.09.a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,2002.02.07,1883,2002.0,Boating,AUSTRALIA,New South Wales,Paramatta River (near Sydney),Kayaking,Paul McNamara,M,35,19h15,C. leucas tooth fragment recovered from kayak,http://sharkattackfile.net/spreadsheets/pdf_di...,2002.02.07
1877,2002.01.30.b,1884,2002.0,Unprovoked,AUSTRALIA,New South Wales,Just north of Fingal Spit,Surfing,Andrew Cribb,M,20,20h45 (Sunset),"Tiger shark, 3 m [10']",http://sharkattackfile.net/spreadsheets/pdf_di...,2002.01.30.b
1888,2001.10.02,1895,2001.0,Unprovoked,AUSTRALIA,Queensland,200 miles offshore,Snorkeling,Katherine Jones,F,20,13h00,Bronze whaler shark?,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.10.02
1961,2001.04.02.a,1968,2001.0,Unprovoked,AUSTRALIA,New South Wales,Nambucca River Entrance,Surfing,Richard Ellis,M,40,10h00,Bronze whaler shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.04.02.a
1969,2001.02.04,1976,2001.0,Unprovoked,AUSTRALIA,New South Wales,Broome Head,Surfing,Mark Butler,M,40,16h15,"Bronze whaler shark, 2.5 m [8.25'] k",http://sharkattackfile.net/spreadsheets/pdf_di...,2001.02.04

5. Extraed unicamente los ataques a mujeres.

In [31]:
df[df['sex-']== 'F']

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25
40,2018.02.23,40,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,55,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.02.23
53,2017.12.31,53,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.12.31
71,2017.10.22,71,2017.0,Unprovoked,AUSTRALIA,South Australia,Normanville,Kayaking / Fishing,Sarah Williams,F,15,Afternoon,"White shark, 4.5 m",http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.22
75,2017.10.05,75,2017.0,Unprovoked,USA,Hawaii,"Kamaole Beach Park, Maui",Snorkeling,female,F,40,12h30,8' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.10.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4151,1958.04.05,4163,1958.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Uvongo,Paddling in knee-deep water,Fay Jones Bester,F,28,11h10,3 m [10'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1958.04.05
4170,1957.12.30,4182,1957.0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Margate,Standing,Julia Painting,F,14,12h40,1.8 m [6'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1957.12.30
4678,1942.12.26,4690,1942.0,Unprovoked,AUSTRALIA,New South Wales,"Bantry Bay, near Ironstone Point, Middle Harbo...",Dog paddling or standing,Denise Rosemary Burch,F,15,10h50,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1942.12.26
4706,1942.01.04,4718,1942.0,Unprovoked,AUSTRALIA,New South Wales,"Egg Rock, Middle Harbor, Sydney",Swimming,Zita Steadman,F,28,15h00,"Bull shark, 4 m [13']",http://sharkattackfile.net/spreadsheets/pdf_di...,1942.01.04
4913,1934.12.31.b,4925,1934.0,Unprovoked,AUSTRALIA,New South Wales,Georges River at Kentucky,Splashing,Beryl Morrin,F,13,20h15,"Tiger shark, 1.5 m [5']",http://sharkattackfile.net/spreadsheets/pdf_di...,1934.12.31.b

6. ¿Cuántas mujeres fueron atacadas en España?

In [32]:
df[(df['sex-']== 'F')&(df['country']=='SPAIN')]['sex-'].value_counts()

F    1
Name: sex-, dtype: int64

7. Extraed los ataques que se hayan producido en el año 2000, 1997 y 2006. Utilizad el método isin() para resolver este ejercicio.

In [33]:
df[df['year'].isin([2000,1997,2006])]

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
1407,2006.12.18,1412,2006.0,Unprovoked,AUSTRALIA,Victoria,"Winki Pop, Bells Beach",Surfing,Peter Galvin,M,25,20h00,2.5 to 3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.12.18
1408,2006.12.11,1413,2006.0,Unprovoked,NEW ZEALAND,North Island,"Raglan, Manu Bay",Surfing,Elliot Paerata-Reid,M,10,11h00,2 to 3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.12.11
1409,2006.12.10,1414,2006.0,Unprovoked,USA,California,"Dillon Beach, Marin County",Surfing,Royce Fraley,M,43,11h50,"White shark, 12' to 15'",http://sharkattackfile.net/spreadsheets/pdf_di...,2006.12.10
1410,2006.12.06,1415,2006.0,Provoked,SOUTH AFRICA,KwaZulu-Natal,Cape Vidal,Fishing,Peter Willoughby,M,25,"""Evening""","Raggedtooth shark, 150-kg",http://sharkattackfile.net/spreadsheets/pdf_di...,2006.12.06
1411,2006.12.02,1416,2006.0,Unprovoked,AUSTRALIA,Western Australia,Wharton Beach,Body boarding,Zac Golebiowski,M,15,07h30,"White shark, 5m",http://sharkattackfile.net/spreadsheets/pdf_di...,2006.12.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2246,1997.05.31.b,2253,1997.0,Unprovoked,USA,Florida,"Flagler Beach, Flagler County",Surfing,Robert Fuller,M,34,11h00,Possibly a sand shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.05.31.b
2247,1997.05.31.a,2254,1997.0,Unprovoked,USA,Florida,"Flagler Beach, Flagler County",Surfing,Johnny Bowden,M,12,11h00,Possibly a sand shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.05.31.a
2252,1997.02.28.a,2259,1997.0,Unprovoked,AUSTRALIA,Queensland,Whitsunday Passage,Scuba diving,Gerald Rauch,M,30,Midday,"Tiger shark, 2m to 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,1997.02.28.a
2256,1997.01.25,2263,1997.0,Unprovoked,AUSTRALIA,Queensland,"Whitehaven Beach, Whitsundays Island",Snorkeling,Derek Burrows,M,27,11h00 / 11h30,1.8 m to 2.1 m [6' to 7'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1997.01.25
2257,1997.01.20,2264,1997.0,Unprovoked,AUSTRALIA,Western Australia,Geraldton,Windsurfing,Werner Schonhofer,M,41,18h00,"Tiger shark, 4.5 m [14'9""]",http://sharkattackfile.net/spreadsheets/pdf_di...,1997.01.20

8. Si extraemos los valores únicos de la columna species nos podemos dar cuenta que está un poco sucia y extraer informacion útil de la misma se puede convertir en algo difícil. En este ejercicio tendréis que extraer los ataques que han ocurrido por tiburón blanco (lo encontraremos en la columna species como algo que contenga white o White). Usad el método str.contains() para resolver este ejercicio.

In [34]:
patron = '(white|White)'
df[df['species-'].str.contains(patron)]['species-'].value_counts()

/var/folders/fk/9dj5qplx5dv2l_dlsz8sf1pw0000gn/T/ipykernel_10898/3114583118.py:2: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  df[df['species-'].str.contains(patron)]['species-'].value_counts()

White shark                                      74
6 m [20'] white shark                            10
5 m [16.5'] white shark                           9
4 m [13'] white shark                             8
White shark, 4 m [13']                            6
                                                 ..
White shark, 4 m white shark                      1
3 m to 4.5 m [10' to 15'] white shark             1
3.7 m to 4.3 m [12' to 14'] white shark           1
White shark, 6m [20']                             1
Thought to involve a 2.6 m [8.5'] white shark     1
Name: species-, Length: 214, dtype: int64

9. Extraed ahora los ataques por tiburón blanco o tigre. Utilizad el método str.contains() para resolver este ejercicio.

In [35]:
patron1 = '(white|White)'
patron2 = "(tiger|Tiger)"

df[df['species-'].str.contains(patron1)]['species-'].value_counts() | df[df['species-'].str.contains(patron2)]['species-'].value_counts()

/var/folders/fk/9dj5qplx5dv2l_dlsz8sf1pw0000gn/T/ipykernel_10898/4046222314.py:4: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  df[df['species-'].str.contains(patron1)]['species-'].value_counts() | df[df['species-'].str.contains(patron2)]['species-'].value_counts()

 Tiger shark, 2.8m                           False
 white shark, 15'                             True
1.5 m [5'] white shark or sevengill shark     True
1.8 m [6'] white shark                        True
12' to 14' white shark                        True
                                             ...
White shark,4.6 m [15']                       True
White shark?                                  True
Whitetip reef shark                           True
Whitetip reef shark, 4' to 6'                 True
juvenile white shark                          True
Name: species-, Length: 306, dtype: bool

10. Utilizando la columna de year cread una nueva columna llamada siglo que tiene siglo-XX o siglo-XXI. Donde el año sea menor que 2000 pondremos siglo-XX y 
el resto de los años siglo-XXI.

In [36]:
df["siglo"] = np.where(df["year"] <2000,"siglo_XX","siglo_XXI")  
df.head()

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2,siglo
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,siglo_XXI
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,siglo_XXI
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,siglo_XXI
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,siglo_XXI
13,2018.05.13.a,13,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,siglo_XXI

In [37]:
#HE APLICADO ESTE METODO PARA ASEGURARME QUE HABIA AÑOS POR DEBAJO DEL 2000 Y POR TANTO SIGLO XX
df["year"].unique()

array([2018., 2017., 2016., 2015., 2014., 2013., 2012., 2011., 2010.,
       2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002., 2001.,
       2000., 1999., 1998., 1997., 1996., 1995., 1994., 1993., 1992.,
       1991., 1990., 1989., 1988., 1987., 1986., 1985., 1984., 1983.,
       1982., 1981., 1980., 1979., 1978., 1977., 1976., 1975., 1974.,
       1973., 1972., 1971., 1970., 1969., 1968., 1967., 1966., 1965.,
       1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957., 1956.,
       1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948., 1947.,
       1946., 1945., 1944., 1943., 1942., 1941., 1940., 1939., 1938.,
       1937., 1936., 1935., 1934., 1932., 1931., 1930., 1929., 1928.,
       1927., 1926., 1925., 1924., 1922., 1919., 1916., 1912., 1906.,
       1905., 1901., 1894., 1892., 1880., 1868.])

11. Guardad como un archivo csv nuevo. Lo usaremos en el pair programming de mañana.

In [38]:
df

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2,siglo
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,siglo_XXI
6,2018.06.03.a,6,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,siglo_XXI
8,2018.05.26.b,8,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,siglo_XXI
10,2018.05.24,10,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,siglo_XXI
13,2018.05.13.a,13,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,siglo_XXI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5528,1901.07.30,5545,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1901.07.30,siglo_XX
5631,1894.11.28,5648,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1894.11.28,siglo_XX
5667,1892.03.02,5684,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1892.03.02,siglo_XX
5797,1880.11.25,5814,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1880.11.25,siglo_XX
5905,1868.05.13,5922,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,http://sharkattackfile.net/spreadsheets/pdf_di...,1868.05.13,siglo_XX

In [39]:
df = df.drop('unnamed:-0',axis=1)
df

,case-number,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2,siglo
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,siglo_XXI
6,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,siglo_XXI
8,2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,siglo_XXI
10,2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,siglo_XXI
13,2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,siglo_XXI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5528,1901.07.30,1901.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Windmill Beach,Swimming,"John Hendrick Adrian Chandler, a prisoner of war",M,29,14h15,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1901.07.30,siglo_XX
5631,1894.11.28,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1894.11.28,siglo_XX
5667,1892.03.02,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1892.03.02,siglo_XX
5797,1880.11.25,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...,1880.11.25,siglo_XX
5905,1868.05.13,1868.0,Unprovoked,INDIA,Hoogly River,Ghat,Standing,male,M,35,Before 10h30,Identified as C. gangeticus by Dr. J. Fayrer,http://sharkattackfile.net/spreadsheets/pdf_di...,1868.05.13,siglo_XX

In [40]:

df.to_csv("../DATA/attacks_Pandas_4.csv")

In [41]:
df1 = pd.read_csv('../DATA/attacks_Pandas_3.csv')
df2 = pd.read_csv('../DATA/attacks_Pandas_4.csv',index_col=0) # le estoy diciendo que unnamed: 0 me la ponga como indice (sin título)

In [42]:
df1.head()

,case-number,unnamed:-0,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2
0,2018.06.25,0,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25
1,2018.06.18,1,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,14h00 -15h00,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18
2,2018.06.09,2,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,07h45,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09
3,2018.06.08,3,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,NaN,NaN,2 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08
4,2018.06.04,4,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,NaN,NaN,"Tiger shark, 3m",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04

In [43]:
df2.head()

,case-number,year,type,country,area,location,activity,name,sex-,age,time,species-,href,case-number.2,siglo
0,2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,siglo_XXI
6,2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,siglo_XXI
8,2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,siglo_XXI
10,2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,siglo_XXI
13,2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,siglo_XXI